package com.smartaudits.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smartaudits.model.Auditoria;
import com.smartaudits.model.Incidencia;
import com.smartaudits.model.TipoFuente;
import com.smartaudits.model.Usuario;
import com.smartaudits.model.dto.AuditoriaRequest;
import com.smartaudits.model.dto.ResultadoAuditoria;
import com.smartaudits.repository.AuditoriaRepository;
import com.smartaudits.repository.HistorialAuditoriaRepository;
import com.smartaudits.repository.IncidenciaRepository;
import com.smartaudits.repository.UsuarioRepository;
import com.smartaudits.service.motor.AnalizadorLegal;
import com.smartaudits.service.motor.EntradaAnalisis;
import com.smartaudits.service.motor.MotorAnalisisLegal;
import com.smartaudits.service.motor.VersionAnalizador;
import org.hibernate.resource.jdbc.spi.StatementInspector;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.NullSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

@DataJpaTest(showSql = false, properties = {
        "spring.config.location=optional:classpath:/phase24e-no-config.properties",
        "spring.jpa.hibernate.ddl-auto=create-drop", "spring.flyway.enabled=false",
        "spring.sql.init.mode=never",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect",
        "spring.jpa.properties.hibernate.session_factory.statement_inspector="
                + "com.smartaudits.service.LegacyResultadosPersistenceTest$SqlCapture",
        "logging.level.root=WARN", "logging.level.org.springframework=WARN"})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@Import({AuditoriaService.class, HistorialService.class, AuditQuotaService.class, ObjectMapper.class})
class LegacyResultadosPersistenceTest {
    @Autowired AuditoriaService service;
    @Autowired AuditoriaRepository audits;
    @Autowired IncidenciaRepository incidents;
    @Autowired UsuarioRepository users;
    @Autowired HistorialAuditoriaRepository history;
    @Autowired TestEntityManager entityManager;
    @Autowired JdbcTemplate jdbc;
    @Autowired ObjectMapper mapper;
    @Autowired PlatformTransactionManager transactions;
    @MockBean AnalizadorLegal motor;

    private static final String ORIGINAL_JSON = """
            { "resumen": "JSON original  ", "puntuacionRiesgo": 23,
              "recomendaciones": ["Una | recomendacion", "Otra"],
              "errores": [{"titulo":"Categoria original","severidad":"MEDIA",
                          "evidencia":"Evidencia original  "}] }
            """;
    private static final LocalDateTime LEGACY_DATE = LocalDateTime.of(2002, 3, 4, 5, 6, 8, 123456000);

    // DDL runs outside test transactions. Hibernate deliberately does not map this table.
    // V1 columns, nullability, unique association and restrictive FK, in H2 syntax.
    @BeforeAll
    static void createLegacyTable(@Autowired JdbcTemplate jdbc) {
        jdbc.execute("""
                CREATE TABLE resultados (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    fecha_resultado TIMESTAMP(6) NOT NULL,
                    puntuacion_cumplimiento INT,
                    recomendaciones_generales TEXT,
                    resumen_general TEXT,
                    auditoria_id BIGINT NOT NULL,
                    CONSTRAINT UK_21ijlu42acphbiah6egbr3kuk UNIQUE (auditoria_id),
                    CONSTRAINT FK6hjf41ajsk7h3fj0td98wio8i FOREIGN KEY (auditoria_id)
                        REFERENCES auditorias(id) ON DELETE RESTRICT
                )
                """);
    }

    @AfterAll
    static void dropLegacyTestTable(@Autowired JdbcTemplate jdbc) {
        jdbc.execute("DROP TABLE resultados");
    }

    @BeforeEach
    void resetCapture() {
        SqlCapture.clear();
    }

    @Test
    void creationPreservesLegacyRowsAndPersistsOnlySnapshotScoreFindingsAndHistory() throws Exception {
        var historical = historical(ORIGINAL_JSON);
        var legacyBefore = jdbc.queryForList("SELECT * FROM resultados ORDER BY id");
        var expected = new MotorAnalisisLegal().analyze(new EntradaAnalisis("zzz", "Aviso Legal"));
        when(motor.version()).thenReturn(new VersionAnalizador("2", "1"));
        when(motor.analyze(any())).thenReturn(expected);
        SqlCapture.clear();

        var response = service.crearAuditoria(request(), historical.getUsuario(), "192.0.2.24");
        entityManager.flush();
        entityManager.clear();
        var stored = audits.findById(response.getId()).orElseThrow();
        var json = mapper.readValue(stored.getResultadoJson(), ResultadoAuditoria.class);
        assertThat(json).isEqualTo(expected);
        assertThat(stored.getPuntuacionRiesgo()).isEqualTo(json.getPuntuacionRiesgo());
        assertThat(response.getResultado()).isEqualTo(expected);
        assertThat(response.getPuntuacionRiesgo()).isEqualTo(stored.getPuntuacionRiesgo());
        assertThat(stored.getVersionMotor()).isEqualTo("2");
        assertThat(stored.getVersionReglas()).isEqualTo("1");
        assertThat(stored.getTipoFuente()).isEqualTo(TipoFuente.MANUAL);
        assertThat(stored.getFechaAnalisis()).isEqualTo(response.getFechaAnalisis());
        assertThat(stored.getIncidencias()).hasSize(expected.getErrores().size());
        for (var error : expected.getErrores()) {
            assertThat(stored.getIncidencias()).filteredOn(i -> i.getRuleId().equals(error.getRuleId()))
                    .singleElement().satisfies(i -> {
                        assertThat(i.getMotor()).isEqualTo(error.getMotor());
                        assertThat(i.getVersion()).isEqualTo(error.getVersion());
                        assertThat(i.getCategoria()).isEqualTo(error.getTitulo());
                        assertThat(i.getDescripcion()).isEqualTo(error.getDescripcion());
                        assertThat(i.getSeveridad()).isEqualTo(error.getSeveridad());
                        assertThat(i.getRecomendacion()).isEqualTo(error.getAccion());
                        assertThat(i.getEvidencia()).isEqualTo(error.getEvidencia());
                        assertThat(i.getImpacto()).isEqualTo(error.getImpacto());
                    });
        }
        assertThat(history.findByAuditoriaIdOrderByFechaAccesoDesc(response.getId()))
                .singleElement().satisfies(event -> assertThat(event.getAccion()).isEqualTo("CREACION"));
        assertNoLegacySql();
        assertThat(jdbc.queryForList("SELECT * FROM resultados ORDER BY id")).isEqualTo(legacyBefore);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM resultados WHERE auditoria_id = ?",
                Long.class, response.getId())).isZero();
        assertThat(entityManager.getEntityManager().getMetamodel().getEntities())
                .noneMatch(entity -> entity.getJavaType().getSimpleName().equals("Resultado"));
    }

    @Test
    void allReadAndDownloadPathsAvoidLegacySqlEvenWithADivergentHistoricalRow() throws Exception {
        var audit = historical(ORIGINAL_JSON);
        var owner = audit.getUsuario();
        var before = snapshot(audit.getId());
        entityManager.clear();
        SqlCapture.clear();

        var detail = service.obtenerAuditoriaPorId(audit.getId(), owner.getId(), false, owner, null);
        assertThat(detail.getResultado()).isEqualTo(mapper.readValue(ORIGINAL_JSON, ResultadoAuditoria.class));
        assertThat(detail.getPuntuacionRiesgo()).isEqualTo(17);
        assertThat(detail.getResultado().getPuntuacionRiesgo()).isEqualTo(23);
        assertThat(detail.getResultado().getErrores()).singleElement().satisfies(error -> {
            assertThat(error.getRuleId()).isNull();
            assertThat(error.getMotor()).isNull();
            assertThat(error.getVersion()).isNull();
        });
        assertNoLegacySql();

        entityManager.clear();
        SqlCapture.clear();
        assertThat(service.obtenerMisAuditorias(owner.getId(), 0, 10).content()).hasSize(1);
        assertNoLegacySql();
        entityManager.clear();
        SqlCapture.clear();
        assertThat(service.obtenerTodasLasAuditorias(0, 10, "").content()).hasSize(1);
        assertNoLegacySql();
        entityManager.clear();
        SqlCapture.clear();
        assertThat(service.obtenerTodasLasAuditorias(0, 10, owner.getNombre()).content()).hasSize(1);
        assertNoLegacySql();
        entityManager.clear();
        SqlCapture.clear();
        service.registrarDescarga(audit.getId(), owner.getId(), false, owner, null);
        entityManager.flush();
        assertNoLegacySql();

        assertThat(snapshot(audit.getId())).isEqualTo(before);
        assertThat(jdbc.queryForObject("SELECT resultado_json FROM auditorias WHERE id = ?", String.class, audit.getId())
                .getBytes(StandardCharsets.UTF_8)).containsExactly(ORIGINAL_JSON.getBytes(StandardCharsets.UTF_8));
        assertThat(jdbc.queryForObject("SELECT fecha_resultado FROM resultados WHERE auditoria_id = ?",
                Timestamp.class, audit.getId()).toLocalDateTime()).isEqualTo(LEGACY_DATE);
        verifyNoInteractions(motor);
    }

    @ParameterizedTest
    @NullSource
    @ValueSource(strings = "{corrupt-json")
    void invalidJsonFailsWithoutLegacyFallbackOrHistoricalChanges(String invalidJson) {
        var audit = historical(invalidJson);
        var owner = audit.getUsuario();
        var before = snapshot(audit.getId());
        entityManager.clear();
        SqlCapture.clear();

        assertThatThrownBy(() -> service.obtenerAuditoriaPorId(audit.getId(), owner.getId(), false, owner, null))
                .isInstanceOf(RuntimeException.class).hasMessage("Error al deserializar resultado");
        entityManager.flush();
        assertNoLegacySql();
        assertThat(snapshot(audit.getId())).isEqualTo(before);
        verifyNoInteractions(motor);
    }

    @Test
    @Transactional(propagation = Propagation.NOT_SUPPORTED)
    void serviceRollbackPreservesExistingLegacyRowsAndLeavesNoNewRepresentations() {
        var transaction = new TransactionTemplate(transactions);
        var historical = transaction.execute(status -> historical(ORIGINAL_JSON));
        try {
            var before = snapshot(historical.getId());
            long auditCount = audits.count(), incidentCount = incidents.count(), historyCount = history.count();
            var legacyBefore = jdbc.queryForList("SELECT * FROM resultados ORDER BY id");
            var invalid = new ResultadoAuditoria.ErrorAuditoria();
            invalid.setTitulo("Missing provenance");
            invalid.setSeveridad("MEDIA");
            var result = new ResultadoAuditoria();
            result.setPuntuacionRiesgo(25);
            result.setErrores(List.of(invalid));
            when(motor.version()).thenReturn(new VersionAnalizador("2", "1"));
            when(motor.analyze(any())).thenReturn(result);
            SqlCapture.clear();

            assertThatThrownBy(() -> service.crearAuditoria(request(), historical.getUsuario(), null))
                    .isInstanceOf(IllegalArgumentException.class);
            assertThat(audits.count()).isEqualTo(auditCount);
            assertThat(incidents.count()).isEqualTo(incidentCount);
            assertThat(history.count()).isEqualTo(historyCount);
            assertNoLegacySql();
            assertThat(jdbc.queryForList("SELECT * FROM resultados ORDER BY id")).isEqualTo(legacyBefore);
            assertThat(snapshot(historical.getId())).isEqualTo(before);
        } finally {
            transaction.executeWithoutResult(status -> {
                jdbc.update("DELETE FROM resultados WHERE auditoria_id = ?", historical.getId());
                jdbc.update("DELETE FROM incidencias WHERE auditoria_id = ?", historical.getId());
                jdbc.update("DELETE FROM auditorias WHERE id = ?", historical.getId());
                users.deleteById(historical.getUsuario().getId());
            });
        }
    }

    private Auditoria historical(String json) {
        var owner = new Usuario();
        owner.setNombre("Legacy owner");
        owner.setEmail("legacy@example.invalid");
        owner.setPassword("unused-test-fixture");
        users.saveAndFlush(owner);
        var audit = new Auditoria();
        audit.setUsuario(owner);
        audit.setTitulo("Historical audit");
        audit.registrarProcedencia("1", "1", LEGACY_DATE.minusSeconds(1), TipoFuente.MANUAL);
        audit.setPuntuacionRiesgo(17);
        audit.setResultadoJson(json);
        var incident = new Incidencia();
        incident.setAuditoria(audit);
        incident.setCategoria("Categoria original");
        incident.setSeveridad("MEDIA");
        incident.setEvidencia("Evidencia original  ");
        incident.registrarProcedencia("R05", "LEGAL_TEXT", "1");
        audit.getIncidencias().add(incident);
        audits.saveAndFlush(audit);
        jdbc.update("""
                INSERT INTO resultados (auditoria_id, fecha_resultado, puntuacion_cumplimiento,
                                        resumen_general, recomendaciones_generales)
                VALUES (?, ?, 91, 'Different legacy summary  ', 'Different legacy recommendations  ')
                """, audit.getId(), Timestamp.valueOf(LEGACY_DATE));
        return audit;
    }

    private List<List<Map<String, Object>>> snapshot(long id) {
        return List.of(jdbc.queryForList("SELECT * FROM auditorias WHERE id = ?", id),
                jdbc.queryForList("SELECT * FROM resultados WHERE auditoria_id = ? ORDER BY id", id),
                jdbc.queryForList("SELECT * FROM incidencias WHERE auditoria_id = ? ORDER BY id", id));
    }

    private AuditoriaRequest request() {
        var request = new AuditoriaRequest();
        request.setTitulo("New audit without a legacy row");
        request.setTipoDocumento("Aviso Legal");
        request.setTextoOriginal("zzz");
        return request;
    }

    private static void assertNoLegacySql() {
        assertThat(SqlCapture.statements.get()).isNotEmpty().noneMatch(sql ->
                Pattern.compile("(?i)(?<![a-z0-9_])resultados(?![a-z0-9_])").matcher(sql).find());
    }

    public static class SqlCapture implements StatementInspector {
        private static final ThreadLocal<List<String>> statements = ThreadLocal.withInitial(ArrayList::new);
        static void clear() { statements.get().clear(); }
        @Override public String inspect(String sql) {
            statements.get().add(sql);
            return sql;
        }
    }
}
